version: '3.8'

services:
  au-osrs-dashboard:
    build: .
    image: au-osrs-dashboard:latest
    restart: unless-stopped
    container_name: au-osrs-dashboard
    ports:
      # Use "8501:8501" for LAN testing or "127.0.0.1:8501:8501" for secure Cloudflare deployment
      - "127.0.0.1:8501:8501"
    volumes:
      # Replace with the absolute path to your database file on the Pi
      - /home/bourke/projects/AU-OSRS-Dashboard/OSRS-Dashboard-ELT/data/optimised_data.db:/data/optimised_data.db:ro
    environment:
      # Set the environment variables for the app to read directly
      - DATA_SOURCE=Local (Development)
      - LOCAL_DB_PATH=/data/optimised_data.db
