[client]
showErrorDetails = "none"
toolbarMode = "viewer"

[theme]
# A custom Green, Gold, and Blue theme.
primaryColor="#D4AF37"
backgroundColor="#0A1931"
secondaryBackgroundColor="#004020"
textColor="#FFFFFF"
